---
- name: Change Azure VM Instance Type
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/instance_details.yml

  tasks:
    - name: Change the VM size
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ new_instance_type }}"
        state: 'present'
      register: vm_details

    - name: Display the VM details
      debug:
        var: vm_details
